### ISSUE TITLE
Requests module error

### ISSUE THREAD

**Issue by blubkens** [RamseyK/ipsw-get#2]
Hi RamseyK,

I'm trying to run your Python script but i run into the following error.

Traceback (most recent call last):
  File "ipsw-get.py", line 4, in <module>
    import request
ImportError: No module named request

I'm no developer and tried to remove the module from the script which gave me another error.

ipsw-get powered by ipsw.me
Could not retrieve firmware metadata from ipsw.me API: global name 'requests' is not defined

Are you able to help me out on the issue above?
Thanks a lot!

**Comment by RamseyK** [comment]
Hello. As stated in the README, you need to install the python requests library. You can do this with “pip install requests”
